server:
  port: 8080
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/sk
    username: sa
    password: sa

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
#  liquibase:
#    change-log: classpath:db/changelog/master.xml



