INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460000', 'POST_OFFICE_ONE', 'Moscow');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460001', 'POST_OFFICE_TWO', 'Paris');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460002', 'POST_OFFICE_THREE', 'London');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460003', 'POST_OFFICE_FOUR', 'New York');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460004', 'POST_OFFICE_FIVE', 'Dubai');

