INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460000', 'POST_OFFICE_ONE', 'Alex');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460001', 'INTERMEDIATE_POST_OFFICE', 'Mike');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460002', 'INTERMEDIATE_POST_OFFICE', 'Ivan');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460003', 'INTERMEDIATE_POST_OFFICE', 'John');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460004', 'POST_OFFICE_TWO', 'Al');
INSERT INTO POST_OFFICE(MAIL_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460005', 'POST_OFFICE_THREE', 'Den');

