INSERT INTO POST_OFFICE(POST_OFFICE_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460000', 'POST_OFFICE_ONE', 'Moscow');
INSERT INTO POST_OFFICE(POST_OFFICE_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460001', 'POST_OFFICE_TWO', 'Paris');
INSERT INTO POST_OFFICE(POST_OFFICE_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460002', 'POST_OFFICE_THREE', 'London');
INSERT INTO POST_OFFICE(POST_OFFICE_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460003', 'POST_OFFICE_FOUR', 'New York');
INSERT INTO POST_OFFICE(POST_OFFICE_INDEX, POST_OFFICE_NAME, RECIPIENT_ADDRESS)
VALUES('460004', 'POST_OFFICE_FIVE', 'Dubai');

INSERT INTO MAILING (UUID, MAIL_TYPE, MAIL_INDEX_RECIPIENT, RECIPIENT_NAME, RECIPIENT_ADDRESS, MAILING_STATUS,
REGISTRATION_TIME, SENTED_TIME, RECEIVED_TIME, POST_OFFICE_ID)
VALUES('cebd667e-41a3-11ee-be56-0242ac120002', 'LETTER', '460000','Alex','Moscow','REGISTRATION', now(), null, null, 5);

INSERT INTO MAILING (UUID, MAIL_TYPE, MAIL_INDEX_RECIPIENT, RECIPIENT_NAME, RECIPIENT_ADDRESS, MAILING_STATUS,
REGISTRATION_TIME, SENTED_TIME, RECEIVED_TIME, POST_OFFICE_ID)
VALUES('cebd667e-41a3-11ee-be56-0242ac120002', 'LETTER', '460000','Alex','Moscow','SENT_BY_POST_OFFICE', now(), now(), null, 1);
